apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodeapp-deployment
  labels:
    app: nodeapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nodeapp
  template:
    metadata:
      labels:
        app: nodeapp
    spec:
      imagePullSecrets:
      - name: docker-secret
      containers:
      - name: nodeapp
        image: tallahmad/nodetest:${BUILD_NUMBER}
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
